name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - run: npm install
    - run: npm run build
  
    - name: Log in to DockerHub
    - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Deploy to DockerHub

      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: username/my-portfolio:latest
